# Generated by Django 5.1.7 on 2025-03-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articulo_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='video',
        ),
        migrations.AddField(
            model_name='articulo',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
